steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_TAG_NAME}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_TAG_NAME}"]
    
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "deploy", 'example', '--image', "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_TAG_NAME}", '--platform', 'managed', '--region', '-us-central1']
